# Generated by Django 4.2.9 on 2024-01-20 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SectionName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=100)),
                ('RollNumber', models.IntegerField(max_length=100)),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.section')),
            ],
        ),
    ]
